### ISSUE TITLE
Authenticating Rack app

### ISSUE THREAD

**Issue by ghost** [esminc/activejob-google_cloud_tasks-http#5]
In the README, it states the following:

> Note that this rack app itself does not have any authentication mechanism.

I am looking to add a simple HTTP Basic AUTH to the rack app, but can't see an obvious way to allow Google Tasks API to specify these credentials when posting to the jobs URL.

**Comment by hibariya** [comment]
You can do that by passing Authorization header as a part of the `headers` parameter for Google Tasks API. Like as follows:

```ruby
Rails.application.config.active_job.queue_adapter = ActiveJob::GoogleCloudTasks::HTTP::Adapter.new(
  project: 'a-gcp-project-name',
  location: 'asia-northeast1',
  url: 'https://an-endpoint-to-perform-jobs.a.run.app/_jobs',
  # ...
  task_options: { # passing content-type header manually with additional authorization header
    headers: {'Content-Type' => 'application/json', 'Authorization' => 'Basic <BASE64-ENCODED-CREDENTIALS>'},
  }
)
```

HTTP request options can be overwritten with `task_options`. Since the option won't be merged and this adapter specifies Content-Type, the original header should also be passed manually. It looks a little awkward but will work.

I think the adapter should provide a better way to specify additional headers for the first place.

**Comment by ghost** [comment]
Brilliant, thanks @hibariya.
